### ISSUE TITLE
Failure with mustache.js on 0.7.1

### ISSUE THREAD

**Issue by csterritt** [marionettejs/backbone.marionette#82]
Hi Derick,

First, thanks for doing Backbone.Marionette -- it's a really nice system.  I feel like I'm learning a lot by reading the code.

Second, of course :-), I have either messed up somehow or found a bug.

I'm using mustache.js for my templating engine, and some code that works with 0.7.0 fails with 0.7.1.

Here's a fiddle that fails: http://jsfiddle.net/CgmqW/4/

I see the following in the console when this runs:

initialize:after start
Entering renderTemplate
TypeError: 'undefined' is not a function (evaluating 'template.slice(i, i + openTag.length)')    mustache.js:341

Any clues appreciated -- thanks!
